apiVersion: ververica.platform/v1
kind: VvpDeployment
metadata:
  name: argocd-top-speed-windowing
  namespace: {{ .Values.k8s_namespace }}
#  annotations:
#    apikeySecretName: apikey-operator
spec:
  syncingMode: PATCH
  deployment:
    userMetadata:
      name: argocd-top-speed-windowing
      namespace: {{ .Values.vvp_namespace }}
    spec:
      state: RUNNING
      deploymentTargetName: {{ .Values.deployment_target }}
      restoreStrategy:
        kind: NONE
      upgradeStrategy:
        kind: STATELESS
      template:
        spec:
          artifact:
            flinkImageRegistry: '{{ .Values.flink_image_registry }}'
            flinkImageTag: '{{ .Values.flink_image_tag }}'
            flinkVersion: '{{ .Values.flink_minor }}'
            jarUri: >-
              https://repo1.maven.org/maven2/org/apache/flink/flink-examples-streaming{{ .Values.scala_suffix }}/{{ .Values.flink_version }}/flink-examples-streaming{{ .Values.scala_suffix }}-{{ .Values.flink_version }}-TopSpeedWindowing.jar
            kind: JAR
  initFields:
    userMetadata:
      displayName: "ArgoCD: Top Speed Windowing"
